### ISSUE TITLE
socat  Bad file descriptor

### ISSUE THREAD

**Issue by tkreuder** [paololazzari/terraform-repl#3]
Hi,

thanks a lot for building this tool. I am looking forward to use it. At the moment I get:
```
 terraform-repl                                                                                                                                                                                
Starting terraform console docker container...
2023/03/27 11:34:02 socat[45075] E write(0, 0x7f8a6a809000, 7): Bad file descriptor
2023/03/27 11:34:02 socat[45085] E write(0, 0x7f84e3009000, 7): Bad file descriptor
write /dev/stdout: input/output error
```
This is my scout version.
```
 socat -V                                                                                                                                                                                      
socat by Gerhard Rieger and contributors - see www.dest-unreach.org
socat version 1.7.4.4 on
```

Any clou what might be wrong here?

**Comment by paololazzari** [comment]
Hi @tkreuder 

Thank you opening this issue. I'll look into it.

In the meanwhile, you can use:

```bash
terraform-repl -no-docker-container-backend
```

the functionality will be identical, just a bit slower compared to when the container backend is used

**Comment by tkreuder** [comment]
Thanks a lot! That works!

This is what I noticed meanwhile:
![image](https://user-images.githubusercontent.com/385110/227930949-45a2db9a-807a-4356-89e0-01308b362050.png)

I do not know, why that is, as aws stuff works properly when I use terraform commands. I also did a `aws configure` again.

**Comment by paololazzari** [comment]
Can you try in a new directory with just a simple .tf file? such as this one:

```terraform
locals {
  a = "foo"
  b = {"nums": [
    1,
    2
  ]}
}
```

**Comment by paololazzari** [comment]
Hi @tkreuder 

Could you try running the latest version (`0.1.5`) against the codebase where the problem manifested itself?
Thanks
