### ISSUE TITLE
Binary for Windows?

### ISSUE THREAD

**Issue by chaoscreater** [paololazzari/terraform-repl#4]
H there,

Is it possible for you to create a binary for Windows?

**Comment by paololazzari** [comment]
Hi @chaoscreater ,

You mean like an .exe?

**Comment by chaoscreater** [comment]
@paololazzari - Yep

**Comment by paololazzari** [comment]
That's not possible as far as I know

**Comment by chaoscreater** [comment]
How is it not possible? Isn't this just a wrapper for the terraform binary? The terraform binary works on Windows. The code just needs to be tweaked to work on Windows.

It's fine if you don't want to work on it because it's too much effort, but saying that it's not possible just doesn't make any sense.

**Comment by paololazzari** [comment]
I thought you were asking whether `terraform-repl` could be compiled into an .exe

If you're asking about a powershell implementation of `terraform-repl`, then yes that is possible

**Comment by chaoscreater** [comment]
yes, if it can be run in Powershell on Windows then it'll be good.
